name: Build Project
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        run: |
          sudo apt update
          sudo apt install libmosquitto openssl git cmake g++-arm-linux-gnueabihf
          git clone https://github.com/fmtlib/fmt
          cd fmt
          mkdir _build
          cd _build
          cmake -DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++ \
          -DCMAKE_INSTALL_PREFIX=/usr/arm-linux-gnueabihf -DFMT_TEST=OFF ..
          make -j4
          sudo make install
          - name: Build
            mkdir _build
            cd _build
            cmake ..
            make