name: Build Project
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Prepare
        run: |
          sudo apt update
          sudo apt install wget git cmake g++-arm-linux-gnueabihf
          git clone https://github.com/fmtlib/fmt
          cd fmt
          mkdir _build
          cd _build
          cmake -DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++ \
          -DCMAKE_INSTALL_PREFIX=/usr/arm-linux-gnueabihf -DFMT_TEST=OFF ..
          make -j4
          sudo make install
          cd ../..
          wget https://www.openssl.org/source/openssl-1.1.1d.tar.gz
          tar xf openssl-1.1.1d.tar.gz
          cd openssl-1.1.1d
          ./Configure linux-generic32 shared --prefix=/usr/arm-linux-gnueabihf --openssldir=/usr/arm-linux-gnueabihf/openssl --cross-compile-prefix=arm-linux-gnueabihf-
          make depend
          make -j4
          make install
          cd ..
          git clone https://github.com/eclipse/mosquitto
          cd mosquitto
          mkdir build
          cd build
          cmake -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc -DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++ -DCMAKE_INSTALL_PREFIX=/usr/arm-linux-gnueabihf ..
          make -j4
          make install
      - name: Build
        run: |
          ls .
          mkdir build
          cd build
          cmake ..
          make
